The goal of this random forest is to predict the political party preferences for a subset of taxpayers by using a random forest classification

In [30]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

In [31]:
# Replace the path with the correct path for your data.
df = pd.read_csv(
    'TaxInfo.csv',
    skipinitialspace=True,
)


In [32]:
df.head(5)

Unnamed: 0     HHI    HHDL  Married  CollegGrads  AHHAge  Cars  \
0           1   49685  227187        0            0     105     0   
1           2   64756 -507342        2            3      68     3   
2           3  115435  521290        1            3      81     2   
3           4   99454  251829        2            1      52     4   
4           5  157274 -472337        0            1      28     1   

   Filed in 2017  Filed in 2016  Filed in 2015 PoliticalParty  
0              1              1              1       Democrat  
1              1              0              0    Independent  
2              0              1              0     Republican  
3              1              0              0     Republican  
4              1              0              1    Independent

In [33]:
#check out data
df.describe()

Unnamed: 0            HHI           HHDL      Married  CollegGrads  \
count  1004.000000    1004.000000    1004.000000  1004.000000  1004.000000   
mean    502.500000  153524.522908   -6666.766932     0.970120     2.595618   
std     289.974137   86167.778113  593751.687936     0.806939     1.687388   
min       1.000000     185.000000 -999994.000000     0.000000     0.000000   
25%     251.750000   82788.500000 -514295.500000     0.000000     1.000000   
50%     502.500000  153788.500000  -11331.500000     1.000000     3.000000   
75%     753.250000  228034.000000  526141.250000     2.000000     4.000000   
max    1004.000000  299700.000000  999628.000000     2.000000     5.000000   

            AHHAge         Cars  Filed in 2017  Filed in 2016  Filed in 2015  
count  1004.000000  1004.000000    1004.000000    1004.000000     1004.00000  
mean     60.577689     2.447211       0.507968       0.512948        0.50996  
std      24.847991     1.701621       0.500186       0.500081        0.50015  
min      18.000000     0.000000       0.000000       0.000000        0.00000  
25%      39.000000     1.000000       0.000000       0.000000        0.00000  
50%      60.000000     2.000000       1.000000       1.000000        1.00000  
75%      81.000000     4.000000       1.000000       1.000000        1.00000  
max     105.000000     5.000000       1.000000       1.000000        1.00000

In [34]:
#drop NA's
df = df.dropna()
df.PoliticalParty.head(20)

0        Democrat
1     Independent
2      Republican
3      Republican
4     Independent
5        Democrat
6      Republican
7        Democrat
8      Republican
9        Democrat
10       Democrat
11    Independent
12     Republican
13    Independent
14     Republican
15     Republican
16     Republican
17     Republican
18       Democrat
19    Independent
Name: PoliticalParty, dtype: object

In [35]:
#check data types
df.dtypes

Unnamed: 0         int64
HHI                int64
HHDL               int64
Married            int64
CollegGrads        int64
AHHAge             int64
Cars               int64
Filed in 2017      int64
Filed in 2016      int64
Filed in 2015      int64
PoliticalParty    object
dtype: object

In [36]:
#Create get dummies for Political Party column
pd.get_dummies(df.PoliticalParty)

Democrat  Independent  Republican
0            1            0           0
1            0            1           0
2            0            0           1
3            0            0           1
4            0            1           0
5            1            0           0
6            0            0           1
7            1            0           0
8            0            0           1
9            1            0           0
10           1            0           0
11           0            1           0
12           0            0           1
13           0            1           0
14           0            0           1
15           0            0           1
16           0            0           1
17           0            0           1
18           1            0           0
19           0            1           0
20           0            1           0
21           0            1           0
22           1            0           0
23           0            1           0
24           0            1           0
25           0            0           1
26           0            0           1
27           0            0           1
28           0            1           0
29           0            0           1
...        ...          ...         ...
974          0            1           0
975          0            0           1
976          0            0           1
977          0            1           0
978          0            0           1
979          0            0           1
980          0            1           0
981          0            0           1
982          0            0           1
983          0            0           1
984          1            0           0
985          1            0           0
986          1            0           0
987          0            0           1
988          1            0           0
989          0            1           0
990          0            1           0
991          1            0           0
992          0            1           0
993          0            0           1
994          0            1           0
995          1            0           0
996          0            0           1
997          1            0           0
998          0            1           0
999          1            0           0
1000         0            0           1
1001         0            0           1
1002         0            0           1
1003         0            0           1

[1004 rows x 3 columns]

In [37]:
df.head(20)

Unnamed: 0     HHI    HHDL  Married  CollegGrads  AHHAge  Cars  \
0            1   49685  227187        0            0     105     0   
1            2   64756 -507342        2            3      68     3   
2            3  115435  521290        1            3      81     2   
3            4   99454  251829        2            1      52     4   
4            5  157274 -472337        0            1      28     1   
5            6  235312  807659        2            2      45     0   
6            7  158461  590203        2            0      74     0   
7            8  205734  416788        2            0      84     5   
8            9  238581  812542        2            3      18     2   
9           10  214597 -193805        2            1      66     5   
10          11  223819  243373        2            1      34     0   
11          12  256348 -376906        0            2      47     1   
12          13  145298 -287587        0            3      62     1   
13          14  225764  735274        2            4      72     4   
14          15  251149  -48468        0            1      87     3   
15          16  215804  196355        1            3      28     4   
16          17  253274 -633752        2            1      94     3   
17          18   98778  949616        0            4      60     3   
18          19  180631 -110700        1            2      68     3   
19          20  212796  709226        1            2      57     3   

    Filed in 2017  Filed in 2016  Filed in 2015 PoliticalParty  
0               1              1              1       Democrat  
1               1              0              0    Independent  
2               0              1              0     Republican  
3               1              0              0     Republican  
4               1              0              1    Independent  
5               1              0              0       Democrat  
6               0              1              0     Republican  
7               0              1              1       Democrat  
8               1              0              0     Republican  
9               1              0              0       Democrat  
10              0              0              0       Democrat  
11              1              0              1    Independent  
12              1              0              1     Republican  
13              1              0              1    Independent  
14              0              1              0     Republican  
15              0              1              1     Republican  
16              0              1              1     Republican  
17              1              0              0     Republican  
18              0              0              0       Democrat  
19              1              0              1    Independent

In [51]:
#Test the model
from sklearn import ensemble
from sklearn.model_selection import cross_val_score

rfc = ensemble.RandomForestClassifier()
Y = pd.get_dummies(df.PoliticalParty)
X = df.drop(['Unnamed: 0','PoliticalParty'], 1)

cross_val_score(rfc, X, Y, cv=9)

/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/sklearn/ensemble/forest.py:246: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/sklearn/ensemble/forest.py:246: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/sklearn/ensemble/forest.py:246: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/sklearn/ensemble/forest.py:246: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 

array([0.1875    , 0.16964286, 0.15178571, 0.11607143, 0.15178571,
       0.14414414, 0.0990991 , 0.10810811, 0.14414414])

In [43]:
# Import and run PCA model 
from sklearn.decomposition import PCA
pca = PCA(n_components=2)
pca.fit(X)
X_pca = pca.transform(X)

In [47]:
rfc = ensemble.RandomForestClassifier()
cross_val_score(rfc, X_pca, Y, cv=2)

/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/sklearn/ensemble/forest.py:246: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/sklearn/ensemble/forest.py:246: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)


array([0.12948207, 0.1314741 ])

In [50]:
X.dtypes

Unnamed: 0       int64
HHI              int64
HHDL             int64
Married          int64
CollegGrads      int64
AHHAge           int64
Cars             int64
Filed in 2017    int64
Filed in 2016    int64
Filed in 2015    int64
dtype: object

In [60]:
#PCA analysis shows that changing the number of varaibles doesn't increase accuracy, so let's change the predicted varaible
#Let's try to alter the predicted variable to whether or not the person is a Democrat, and retest the model
df['Democrat_YesNo'] = df['PoliticalParty'].apply(lambda x: True if x == 'Democrat' else False)

In [68]:
#retest the model
rfc = ensemble.RandomForestClassifier()
Y = df.Democrat_YesNo
X = df.drop(['PoliticalParty', 'Democrat_YesNo', 'Unnamed: 0'], 1)

cross_val_score(rfc, X, Y, cv=9)

/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/sklearn/ensemble/forest.py:246: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/sklearn/ensemble/forest.py:246: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/sklearn/ensemble/forest.py:246: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/sklearn/ensemble/forest.py:246: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 

array([0.62831858, 0.61061947, 0.61607143, 0.6036036 , 0.63063063,
       0.66666667, 0.64864865, 0.63963964, 0.66666667])

In [66]:
#That gave us much better accuracy, ranging between ~63 and ~67 percent

['Unnamed: 0',
 'HHI',
 'HHDL',
 'Married',
 'CollegGrads',
 'AHHAge',
 'Cars',
 'Filed in 2017',
 'Filed in 2016',
 'Filed in 2015',
 'PoliticalParty',
 'Democrat_YesNo']